version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=techplayground
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5111:5432"
  sqlpad:
    image: sqlpad/sqlpad:5.5
    depends_on: postgres
    environment:
      SQLPAD_AUTH_DISABLED: "true"
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: "admin"
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__psql__name: psql
      SQLPAD_CONNECTIONS__psql__driver: postgres
      SQLPAD_CONNECTIONS__psql__host: postgres
      SQLPAD_CONNECTIONS__psql__username: postgres
      SQLPAD_CONNECTIONS__psql__multiStatementTransactionEnabled: "true"
      SQLPAD_CONNECTIONS__psql__idleTimeoutSeconds: 86400
    ports:
      - "3001:3000"
  apis:
    build: ./apis
    depends_on:
      - postgres
      - mongo
    environment:
      MONGODB_HOST: mongo
      POSTGRESDB_HOST: postgres
    ports:
    - 8080:8080
